<a href="https://colab.research.google.com/github/joannediaz04/ADVANCED-DATA-VISUALIZATION-LAB-11/blob/main/ADVANCED_DATA_VISUALIZATION_LAB_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
price=[2,1,10]
type(price)

list

In [2]:
quantity_sold=[17,40,1]
type(quantity_sold)

list

In [5]:
import numpy as np

In [7]:
price_array=np.array(price)
quantity_sold_array=np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [8]:
price_array*quantity_sold_array

array([34, 40, 10])

In [9]:
cost_array=np.array([0.25,0.50,0.00])

In [11]:
profit_array=price_array-cost_array
print(profit_array)

[ 1.75  0.5  10.  ]


In [12]:
profit_array>2.00

array([False, False,  True])

In [13]:
price_array=price_array+[7]
print(price_array)

[ 9  8 17]


In [14]:
price_array=price_array-[7]

In [15]:
price_array=np.append(price_array,7)
print(price_array)

[ 2  1 10  7]


In [16]:
price_array=np.append(price_array,[4.50,3,4,9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [17]:
print(price_array.dtype)

float64


In [18]:
price_array=np.delete(price_array,-1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [19]:
price_array[2]=12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]
